### ISSUE TITLE
コンストラクタが結果出力関数となっていることによる重複が複数個所にある

### ISSUE THREAD

**Issue by genokamura** [ka-ma-ta/OBJECT-ORIENTATION#1]
意図を示すコードを書く、という観点では、コンストラクタで結果出力はしないほうがよいと思います。
メソッドを切り出して、インスタンス生成後に結果出力関数を呼び出すような実装にしましょう。

https://github.com/ka-ma-ta/OBJECT-ORIENTATION/blob/d2e2c1213aaeeff7ae6b1d32b3c6f79f46578932/question01.php#L23

その後の課題でも、結果出力のための`echo`呼び出しが多数書かれていますが、それらの重複排除ができます。

**Comment by ka-ma-ta** [comment]
①結果出力関数をCarクラスから切り離しました。
https://github.com/ka-ma-ta/OBJECT-ORIENTATION/blob/c71fec8ead5597f8577303e6f896953053c79183/question01.php#L30

②結果出力関数をインスタンス作成後に、都度呼び出すようにしました。
https://github.com/ka-ma-ta/OBJECT-ORIENTATION/blob/c71fec8ead5597f8577303e6f896953053c79183/question01.php#L45

③コンストラクタ関数では、インスタンス作成時に初期値をセットするようにしました。
https://github.com/ka-ma-ta/OBJECT-ORIENTATION/blob/c71fec8ead5597f8577303e6f896953053c79183/question01.php#L21

**Comment by genokamura** [comment]
こちらはOKです。
