### ISSUE TITLE
クラス図に書いていただいている実装になっていません。

### ISSUE THREAD

**Issue by genokamura** [ka-ma-ta/OBJECT-ORIENTATION#2]
クラス図が無視された実装となっているように見受けられます。
liftUp、およびliftDownメソッドを定義・実装しましょう。

https://github.com/ka-ma-ta/OBJECT-ORIENTATION/blob/d2e2c1213aaeeff7ae6b1d32b3c6f79f46578932/question02.php#L47

**Comment by ka-ma-ta** [comment]
Ferrariクラス作成時に、liftUp、liftDownメソッドを作成しました。
https://github.com/ka-ma-ta/OBJECT-ORIENTATION/blob/c71fec8ead5597f8577303e6f896953053c79183/question02.php#L35
https://github.com/ka-ma-ta/OBJECT-ORIENTATION/blob/c71fec8ead5597f8577303e6f896953053c79183/question02.php#L46

**Comment by genokamura** [comment]
こちらはOKです。
